version: "3.8"

services:
    api:
        build: .
        ports:
            - "3333:3333"
        environment:
            - API_PORT=3333
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=postgres
        volumes:
            - .:/usr/src/app
        command: go run cmd/main.go -b 0.0.0.0
        # command: air cmd/main.go -b 0.0.0.0
        depends_on:
            - db

    db:
        image: postgres:alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
    postgres:
